version: "3.3"
networks:
  arrow-dev-network:
    driver: bridge
    ipam:
     config:
       - subnet: 172.20.0.0/24
services:
  redis:
    container_name: redis
    image: redis:5-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      arrow-dev-network:
        ipv4_address: 172.20.0.2
  db:
    container_name: postgres
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: Mamma1.2
    restart: always
    ports:
      - "5432:5432"
    networks:
      arrow-dev-network:
        ipv4_address: 172.20.0.3
  rabbit:
    container_name: rabbit
    image: rabbitmq:3.7-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: arrow
      RABBITMQ_DEFAULT_PASS: Mamma1.2
    restart: always
    ports:
      - "15672:15672"
    networks:
      arrow-dev-network:
        ipv4_address: 172.20.0.4